server:
  host: "127.0.0.1"
  port: 9092
  max_connections: 1000
  connection_idle_timeout: "300s"

storage:
  data_dir: "data"
  segment_size: 1073741824 # 1GB
  index_interval_bytes: 4096 # 4KB
  retention_hours: 168
  max_segment_size: 1073741824
  max_segments: 10

log:
  level: "info"
  file: "bifrost.log"
  rotation:
    max_size: 104857600 # 100MB
    max_files: 5 