server:
  host: 127.0.0.1
  port: 8080
  max_connections: 1024
  connection_idle_timeout: 60s

storage:
  engine: "mmap"
  segment_size: 1073741824 # 1GB
  index_interval_bytes: 4096 # 4KB
  retention_policy_bytes: 10737418240 # 10GB
  retention_policy_ms: 604800000 # 7 days

log:
  level: "info"

broker:
  id: 0
  advertised_host: "127.0.0.1"
  advertised_port: 9092
  data_dir: "data" 
  flush_interval_ms: 1000
  cleanup_interval_ms: 5000